name: Package

on: [push]

env:
  VERSION: ${{ github.ref_name }}

jobs:
  build:
    name: Build
    strategy:
      matrix:
        type: [debug, release]
        size: [UINT8, UINT16, UINT32, UINT64]

    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ghcr.io/throttr/throttr:${{ env.VERSION }}-${{ matrix.type }}-${{ matrix.size }}
          build-args: |
            TYPE=${{ matrix.type }}
            SIZE=${{ matrix.size }}
