name: Package

on:
  push:
    branches:
      - master
    tags:
      - '*'

env:
  VERSION: ${{ github.ref_name }}

jobs:
  build:
    name: Build
    strategy:
      matrix:
        type: [debug, release]
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref_type == 'tag' }}
          tags: ghcr.io/throttr/throttr:${{ env.VERSION }}-${{ matrix.type }}
          build-args: |
            TYPE=${{ matrix.type }}
