name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    name: Build and create release

    strategy:
      matrix:
        type: [Release, Debug]
        size: [UINT8, UINT16, UINT32, UINT64]
        sockets: [UNIX_BASED, TCP_BASED]
        metrics: [METRICS_ENABLED, METRICS_DISABLED]
        platform: [linux/amd64, linux/arm64]

    runs-on: ${{ matrix.platform == 'linux/arm64' && 'ubuntu-22.04-arm' || 'ubuntu-latest' }}

    container:
      image: ghcr.io/throttr/builder-alpine:1.87.0-debug

    steps:
      - uses: actions/checkout@v4

      - name: Build and test
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.type }} -DBUILD_TESTS=OFF -DRUNTIME_VALUE_SIZE=${{ matrix.size }} -DENABLE_UNIX_SOCKETS=${{ matrix.sockets == 'SOCKETS_BASED' && 'ON' || 'OFF' }} -DENABLE_FEATURE_METRICS=${{ matrix.metrics == 'METRICS_ENABLED' && 'ON' || 'OFF' }} -DENABLE_STATIC_LINKING=ON
          make -j4
          cd ..
          mkdir -p dist
          cp build/throttr dist/
          cp LICENSE dist/
          cd dist && zip throttr-${{ matrix.type }}-${{ matrix.size }}-${{ matrix.platform == 'linux/arm64' && 'ARM64' || 'AMD64' }}-${{ matrix.sockets == 'UNIX_BASED' && 'UNIX' || 'TCP' }}-${{ matrix.metrics == 'METRICS_ENABLED' && 'metrics-enabled' || 'metrics-disabled' }}.zip throttr LICENSE

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/throttr-${{ matrix.type }}-${{ matrix.size }}-${{ matrix.platform == 'linux/arm64' && 'ARM64' || 'AMD64' }}-${{ matrix.sockets == 'UNIX_BASED' && 'UNIX' || 'TCP' }}-${{ matrix.metrics == 'METRICS_ENABLED' && 'metrics-enabled' || 'metrics-disabled' }}.zip
