name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    name: Build and create release

    strategy:
      matrix:
        type: [Release, Debug]
        size: [UINT8, UINT16, UINT32, UINT64]
        metrics: [METRICS_ENABLED, METRICS_DISABLED]

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/throttr/builder-alpine:1.87.0-${{ matrix.type }}

    steps:
      - uses: actions/checkout@v4

      - name: Build and test
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.type }} -DBUILD_TESTS=OFF -DRUNTIME_VALUE_SIZE=${{ matrix.size }} -DENABLE_FEATURE_METRICS=${{ matrix.metrics == 'METRICS_ENABLED' && 'ON' || 'OFF' }} -DENABLE_STATIC_LINKING=ON
          make -j4
          strip --strip-all throttr
          cd ..
          mkdir -p dist
          cp build/throttr dist/
          cp LICENSE dist/
          cd dist && zip throttr-${{ matrix.type }}-${{ matrix.size }}-amd64-${{ matrix.metrics == 'METRICS_ENABLED' && 'metrics-enabled' || 'metrics-disabled' }}.zip throttr LICENSE

      - name: Upload release asset
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          files: dist/throttr-${{ matrix.type }}-${{ matrix.size }}-amd64-${{ matrix.metrics == 'METRICS_ENABLED' && 'metrics-enabled' || 'metrics-disabled' }}.zip
